apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poirot-data
  namespace: {{ include "poirot.namespace" . }}
  labels:
    {{- include "poirot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poirot-config
  namespace: {{ include "poirot.namespace" . }}
  labels:
    {{- include "poirot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: {{ include "poirot.namespace" . }}
  labels:
    {{- include "poirot.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.keycloak.accessMode }}
  {{- if .Values.persistence.keycloak.storageClass }}
  storageClassName: {{ .Values.persistence.keycloak.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.keycloak.size }}
{{- end }}
