apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: {{ include "poirot.namespace" . }}
  labels:
    app: dashboard
    {{- include "poirot.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dashboard-scanner-exec
  namespace: {{ include "poirot.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-scanner-exec
  namespace: {{ include "poirot.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: dashboard
    namespace: {{ include "poirot.namespace" . }}
roleRef:
  kind: Role
  name: dashboard-scanner-exec
  apiGroup: rbac.authorization.k8s.io
